### ISSUE TITLE
Tracking Issues

### ISSUE THREAD

**Issue by FlyingThaCat** [FlyingThaCat/ytmc#1]
This Issues Mostly Use For Tracking Bugs or Feature Improvement

**Comment by FlyingThaCat** [comment]
- [x] Some Indexing problem on some artist page
![image](https://github.com/FlyingThaCat/ytmc/assets/95353217/b28c8d13-7061-421d-8ed5-df538019927f)
- [ ] Some Overlap issue found at some artist page
![image](https://github.com/FlyingThaCat/ytmc/assets/95353217/7e8f6010-73e8-462c-9d64-196c6dad5259)
- [x] Top Songs needs more adjustment thumbnail resolution
![image](https://github.com/FlyingThaCat/ytmc/assets/95353217/6c69d845-83ae-435d-914d-7ea13dceed6f)

**Comment by FlyingThaCat** [comment]
- [x] some artist doesnt have browse id ???
![image](https://github.com/FlyingThaCat/ytmc/assets/95353217/f84d6e16-47be-437e-8de0-d034167e1648)

**Comment by FlyingThaCat** [comment]
- [ ] Some data had weird issue ??? (artistID: UCKnv--zTxRcjwzxE7gujBaA)
![image](https://github.com/FlyingThaCat/ytmc/assets/95353217/3a71a2ba-20d0-4574-a00e-ba1d3a2a482d)

**Comment by FlyingThaCat** [comment]
- [ ] Validate itemCount
![image](https://github.com/FlyingThaCat/ytmc/assets/95353217/b1311e36-ac14-4813-902f-1b463e8695bf)

**Comment by FlyingThaCat** [comment]
this is closed since i dont know how to fix audio service in windows probably will migrate to android studio and make it native :)
